### ISSUE TITLE
Visual representation of org chart (network map)

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-website#24]
I am so very interested in help the structure of EDGI (both at high-level and sub-project level) to become more legible is a visual way :)

Example: [Capacity & Governance doc with diagram](https://docs.google.com/document/d/15PNLit4boFHSUzmu_oXTG0aVgaZR-mVnDp5BNujN5BU/edit)

A personal attempt by me to make it more legible to myself: https://littlesis.org/maps/2305-edgi-landscape

Context: https://edgi.slack.com/conversation/web_monitoring/p1496690227634486

**Comment by dcwalk** [comment]
So many +1s about making the structure legible, have wanted this for a while :)

Lourdes is missing! and Justin!
Gretchen is part of Web Monitoring,
Also Archiving WG has also operated as a "tech team," and my sense is we have a couple of other shadow "teams" that aren't quite WGs (or something confusing like that)-- like:
- website/communications
- funding/budgeting
- (potentially) dispute mediation?

Also, I am assuming this only relies on people listed on the website? I think we might want something at a lower level of fidelity that doesn't have to be updated as frequently (e.g., maybe wgs, coordinators, and projects) rather than each individual and their listed affiliation?

**Comment by lourdesvera** [comment]
🥇 done, finally
