### ISSUE TITLE
Update Global Navigation

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/edgi-website#31]
From 2017-08-07 website meeting:
> About section add first menu item of “Mission”.”
> - 4S meeting mission statement -  similar structure but content to change.
> - Link to EDGI member Protocol PDF - have it separate but “Our Protocol” 
>   - We can also create it as a publication type (first iteration) on the list of total publications 
> Make global Nav consistent:
> - “About” “Publications “events” items do not go anywhere “#”
> - Add “View all” under publications
> - Add Mission under About

**Comment by lourdesvera** [comment]
- updated the header navigator to make top text not go anywhere w/ "#". To keep it consistent, I broke Press up into highlights, member op eds, and full coverage. I added "posts" under Blog. 
-Right now, instead of "mission," the about page under About says "Overview". Waiting on the mission statement after 4S.
