### ISSUE TITLE
Partners page: add some explanation?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/edgi-website#65]
The [Partners page](https://envirodatagov.org/about/partners/) is just a big list of partners. Would it be helpful to add some text explaining what "partnership" means to us, or past projects?

**Comment by Frijol** [comment]
cc @EDGI-Comms

**Comment by EDGI-Comms** [comment]
Yes I agree the Partners page needs help! I think we should just use linked logos or names under a title/description, rather than an airtable. And I think we should formally reach out to organizations like Union of Concerned Scientists and asking them if they'd like to be considered partners as well, or part of our coalition.
